<?php
/**
 * @file
 * os2sub_frontpage.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function os2sub_frontpage_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-velkomst-body'.
  $field_instances['node-velkomst-body'] = array(
    'bundle' => 'velkomst',
    'default_value' => array(
      0 => array(
        'summary' => '',
        'value' => '',
        'format' => 'full_html',
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'list' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'list_advanced' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'list_simple' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'spotbox' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'trim_length' => 600,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'body',
    'label' => 'Body',
    'required' => FALSE,
    'settings' => array(
      'display_summary' => TRUE,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'module' => 'text',
      'settings' => array(
        'rows' => 20,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'node-velkomst-field_baggrund'.
  $field_instances['node-velkomst-field_baggrund'] = array(
    'bundle' => 'velkomst',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'backstretch',
        'settings' => array(
          'center_x' => 1,
          'center_y' => 1,
          'delta' => '',
          'duration' => 5000,
          'element' => 'other',
          'element_other' => '.content',
          'fade' => 0,
          'field' => '',
          'image_style' => 'os2web_cover',
          'random' => 1,
        ),
        'type' => 'backstretch',
        'weight' => 1,
      ),
      'list' => array(
        'label' => 'hidden',
        'module' => 'backstretch',
        'settings' => array(
          'center_x' => 1,
          'center_y' => 1,
          'delta' => '',
          'duration' => 5000,
          'element' => 'other',
          'element_other' => '.content',
          'fade' => 0,
          'field' => '',
          'image_style' => 'os2web_cover',
          'random' => 1,
        ),
        'type' => 'backstretch',
        'weight' => 1,
      ),
      'list_advanced' => array(
        'label' => 'hidden',
        'module' => 'backstretch',
        'settings' => array(
          'center_x' => 1,
          'center_y' => 1,
          'delta' => '',
          'duration' => 5000,
          'element' => 'other',
          'element_other' => '.content',
          'fade' => 0,
          'field' => '',
          'image_style' => 'os2web_cover',
          'random' => 1,
        ),
        'type' => 'backstretch',
        'weight' => 1,
      ),
      'list_simple' => array(
        'label' => 'hidden',
        'module' => 'backstretch',
        'settings' => array(
          'center_x' => 1,
          'center_y' => 1,
          'delta' => '',
          'duration' => 5000,
          'element' => 'other',
          'element_other' => '.content',
          'fade' => 0,
          'field' => '',
          'image_style' => 'os2web_cover',
          'random' => 1,
        ),
        'type' => 'backstretch',
        'weight' => 1,
      ),
      'spotbox' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_baggrund',
    'label' => 'Baggrund',
    'required' => 0,
    'settings' => array(
      'alt_field' => 0,
      'default_image' => 0,
      'epsacrop' => array(
        'styles' => array(
          'os2sub_220x130' => 0,
          'os2sub_300x175' => 0,
          'os2sub_banner' => 0,
          'os2sub_normal_imagesize' => 0,
          'os2sub_small_imagesize' => 0,
          'os2web_spotbox_image' => 0,
        ),
      ),
      'file_directory' => '',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '',
      'max_resolution' => '',
      'min_resolution' => '1920x1165',
      'title_field' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'media',
      'settings' => array(
        'allowed_schemes' => array(
          'public' => 'public',
          'youtube' => 0,
        ),
        'allowed_types' => array(
          'audio' => 0,
          'document' => 0,
          'image' => 'image',
          'video' => 0,
        ),
        'browser_plugins' => array(
          'media_default--media_browser_1' => 'media_default--media_browser_1',
          'media_default--media_browser_my_files' => 'media_default--media_browser_my_files',
          'media_internet' => 0,
          'upload' => 'upload',
          'youtube' => 0,
        ),
        'progress_indicator' => 'throbber',
      ),
      'type' => 'media_generic',
      'weight' => 6,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Baggrund');
  t('Body');

  return $field_instances;
}
