<?php
/**
 * @file
 * os2web_spotbox.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function os2web_spotbox_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_os2web_spotbox_big_image'
  $field_bases['field_os2web_spotbox_big_image'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_os2web_spotbox_big_image',
    'indexes' => array(
      'fid' => array(
        0 => 'fid',
      ),
    ),
    'locked' => 0,
    'module' => 'image',
    'settings' => array(
      'default_image' => 0,
      'uri_scheme' => 'public',
    ),
    'translatable' => 0,
    'type' => 'image',
  );

  // Exported field_base: 'field_os2web_spotbox_text'
  $field_bases['field_os2web_spotbox_text'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_os2web_spotbox_text',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'text_long',
  );

  return $field_bases;
}
