<?php
/**
 * @file
 * Code for the OS2sub Banner feature.
 */


include_once 'os2sub_banner.features.inc';

function os2sub_banner_install() {
  $newnode = new stdClass();
  $newnode->title = 'Velkommen til den nye hjemmeside';
  $newnode->body = 'Skift indholdet af denne side.';

  global $user;

  $newnode->uid = $user->uid;
  $newnode->name = $user->name;
  $newnode->type = 'banner';
  $newNode->format = 3;     // 1 means filtered html, 2 means full html, 3 is php
  $newnode->status = 1;     // 1 means published
  $newnode->promote = 1;
  $newnode->language = 'da';
  $newnode = node_submit( $newnode );
  node_save( $newnode ); 
}