<?php

/**
 * Implements hook_block_info().
 */
function os2sub_social_share_block_info() {
  $blocks['os2sub_social_share'] = array(
    'info' => t('OS2Sub social share links'),
    //'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function os2sub_social_share_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'os2sub_social_share':
      $block['subject'] = t('Social share');
      $block['content'] = os2sub_social_share_content();
      break;
  }
  return $block;
}

function os2sub_social_share_content() {
  $node = menu_get_object();
  if ($node) {
    $title = $node->title;
    $url = url(drupal_get_path_alias('node/' . $node->nid), array('absolute' => TRUE));
  } elseif ($term = menu_get_object('taxonomy_term', 2)) {
    $title = $term->name;
    $url = url(drupal_get_path_alias('taxonomy/term/' . $term->tid), array('absolute' => TRUE));
  }
// this is where the $items get sent to your default MYMODULE_BLOCK.tpl.php that gets
// registered below
  if (isset($url)) {
    $current_object = array('url' => $url, 'title' => $title);

    return theme('os2sub_social_share', array('current_node' => $current_object));
  }
}

//here you are registering your default tpl for the above block
function os2sub_social_share_theme() {
  return array(
    'os2sub_social_share' => array(
      'variables' => array(
        'current_node' => NULL,
      ),
      'template' => 'os2sub-social-share',
      'path' => drupal_get_path('module', 'os2sub_social_share') . '/templates',
    ),
  );
}