<?php

/**
 * @file
 * kultunaut_import.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function kultunaut_import_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'eq_taxonomy_term'.
  $field_bases['eq_taxonomy_term'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(
      0 => 'entityqueue_subqueue',
    ),
    'field_name' => 'eq_taxonomy_term',
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'handler' => 'entityqueue',
      'handler_settings' => array(
        'behaviors' => array(
          'entityqueue' => array(
            'status' => 1,
          ),
        ),
      ),
      'target_type' => 'taxonomy_term',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  return $field_bases;
}
